services:
  shinyproxy:
    container_name: shinyproxy
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - "./application.yml:/opt/shinyproxy/application.yml:z"
    networks: 
      - workstudio-net
    ports:
      - 8888:8080
networks: 
  workstudio-net:
    name: "workstudio-net"
      